### ISSUE TITLE
Dubbi su come usare git?

### ISSUE THREAD

**Issue by VirtuContraFurore** [VirtuContraFurore/CopeApp-alfa#1]
Se avete dubbi su come usare git potete scrivere qua e cercherò di aiutarvi, così iniziate a vedere cosa ci si può fare. Fra le cose ci sono queste chat...!!

**Comment by FabioTessaro** [comment]
Sarebbe per i problemi sta parte 😂

**Comment by VirtuContraFurore** [comment]
esatto, se non avete dubbi non state studiando
